# Generated by Django 6.0.2 on 2026-05-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OGRENCI', 'Öğrenci'), ('AKADEMISYEN', 'Akademisyen'), ('YONETICI', 'Yönetici')], max_length=15),
        ),
    ]
