# Generated by Django 6.0.2 on 2026-05-03 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DersKayitDonemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('donem', models.CharField(choices=[('GUZ', 'Güz'), ('BAHAR', 'Bahar')], max_length=10)),
                ('baslangic', models.DateTimeField()),
                ('bitis', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Ders Kayıt Dönemi',
                'verbose_name_plural': 'Ders Kayıt Dönemleri',
            },
        ),
        migrations.CreateModel(
            name='DersKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vize_notu', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_notu', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('harf_notu', models.CharField(blank=True, choices=[('AA', 'AA (4.00)'), ('BA', 'BA (3.50)'), ('BB', 'BB (3.00)'), ('CB', 'CB (2.50)'), ('CC', 'CC (2.00)'), ('DC', 'DC (1.50)'), ('DD', 'DD (1.00)'), ('FF', 'FF (0.00)')], max_length=2, null=True)),
                ('onay_durumu', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20)),
                ('donem_dersi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.donemdersi')),
            ],
            options={
                'verbose_name': 'Ders Kaydı',
                'verbose_name_plural': 'Ders Kayıtları',
            },
        ),
    ]
