# Generated by Django 6.0.2 on 2026-05-03 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derskaydi',
            name='ogrenci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.ogrenci'),
        ),
        migrations.AddConstraint(
            model_name='derskayitdonemi',
            constraint=models.UniqueConstraint(fields=('yil', 'donem'), name='unique_kayit_donemi'),
        ),
        migrations.AddConstraint(
            model_name='derskaydi',
            constraint=models.UniqueConstraint(fields=('ogrenci', 'donem_dersi'), name='unique_ogrenci_donem_ders'),
        ),
    ]
