# Generated by Django 6.0.2 on 2026-05-03 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonemDersi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('donem', models.CharField(choices=[('GUZ', 'Güz'), ('BAHAR', 'Bahar')], max_length=10)),
                ('kontenjan', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('aktiflik_durumu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dönem Dersi',
                'verbose_name_plural': 'Dönem Dersleri',
            },
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_kodu', models.CharField(max_length=20, unique=True)),
                ('ad', models.CharField(max_length=100)),
                ('kredi', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('min_sinif', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dersler', to='departments.bolum')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
            },
        ),
    ]
