# Generated by Django 6.0.2 on 2026-05-03 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donemdersi',
            name='akademisyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.akademisyen'),
        ),
        migrations.AddField(
            model_name='donemdersi',
            name='ders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.ders'),
        ),
        migrations.AddConstraint(
            model_name='donemdersi',
            constraint=models.UniqueConstraint(fields=('ders', 'akademisyen', 'yil', 'donem'), name='unique_donem_dersi'),
        ),
    ]
