# Generated by Django 6.0.2 on 2026-05-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donemdersi',
            name='aktiflik_durumu',
            field=models.BooleanField(default=False),
        ),
    ]
